name: Development CI

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - name: Run integration tests
        run: npm run test:e2e
      - name: Run unit tests with code coverage
        run: npm run test:cov
      - name: Checkception - Run action locally with its own coverage
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: 'coverage/clover.xml'
          required-percentage: 80
